#
# Digital Voice Modem - Desktop Dispatch Console
#
# Full path to local key YAML file (see keys.example.clear for formatting)
#keyFile: "Full/Path/To/Keyfile.clear"
#
# FNE Masters
#
systems:
    # Textual name for internal and external reference to this system
  - name: "System 1"
    # Textual name to idenitify this peer in the FNE
    identity: "CONS OP1"
    # FNE Address
    address: "127.0.0.1"
    # FNE Port
    port: 62031
    # Peer ID for FNE
    peerId: 1234567
    # Radio ID transmitted traffic will come from
    rid: "12345"
    # FNE Password
    password: "RPT_PASSWORD"
    # FNE Encrypted flag
    encrypted: false
    # Preshared FNE encryption key
    presharedKey: "123ABC1234"
    # Path to Radio Alias file for this system
    #aliasPath: "Full/Path/To/alias.yml"
    
#
# Zones (each zone becomes a tab)
#
zones:
    # Textual name of the zone (this becomes the tab name)
  - name: "Primary"
    # List of channels in this zone/tab
    channels:
        # Textual name of channel
      - name: "Channel 1"
        # System name this channel is linked to
        system: "System 1"
        # Talkgroup Id to send and receive traffic
        tgid: "2001"
        # Encryption Key Id (If 0 or blank, will be assumed clear)
        keyId: 0x50
        # Algorithm AES ("aes"), DES-OFB ("des"), ADP/ARC4 ("arc4"), None ("none")
        algo: "aes"
        # Ignored now, we use dvmfne KMM support (This will be used in the future to ovveride FNE KMM support)
        encryptionKey: null
        # Voice mode DMR ("dmr"), P25 ("p25")
        mode: "p25"
      - name: "Channel 2"
        system: "System 1"
        tgid: "15002"
      - name: "Channel 3"
        system: "System 1"
        tgid: "15003"

  - name: "Secondary"
    channels:
      - name: "Channel A"
        system: "System 1"
        tgid: "16001"
      - name: "Channel B"
        system: "System 1"
        tgid: "16002"

  - name: "Emergency"
    channels:
      - name: "Channel C"
        system: "System 1"
        tgid: "16002"
